Repository p2devs/InkNest, pull requests merged in 2024-07, with the labels that each got.

#8 Add Enhancements to Home and Settings Screens and Update Dependencies
  android/app/build.gradle
  android/build.gradle
  firebase.json
  ios/InkNest.xcodeproj/project.pbxproj
  ios/InkNest/Info.plist
  ios/InkNest/PrivacyInfo.xcprivacy
  ios/Podfile.lock
  package.json
  src/Components/Func/AnimeVideoFunc.js
  src/Components/Func/HomeFunc.js
  src/Components/UIComp/Button.js
  src/Components/UIComp/ComicBookFooter.js
  src/Components/UIComp/Header.js
  src/Components/UIComp/HomeRenderItem.js
  src/Components/UIComp/MarkDown.js
  src/Components/UIComp/Skeleton.js
  src/Constants/Navigation.js
  src/Navigation/AppNavigation.js
  src/Navigation/BottomNavigation/BottomNavigation.tsx
  src/Navigation/index.js
  src/Redux/Actions/GlobalActions.js
  src/Redux/Controller/Interceptor.js
  src/Redux/Reducers/index.js
  src/Screens/AboutUs/index.js
  src/Screens/Anime/Details/index.js
  src/Screens/Anime/Home/AnimeHome.js
  src/Screens/Anime/Home/ViewAll.js
  src/Screens/Anime/Video/index.js
  src/Screens/Anime/index.js
  src/Screens/Comic/Book/ComicBook.js
  src/Screens/Comic/Details/ComicDetails.js
  src/Screens/Comic/Home/Home.js
  src/Screens/Comic/index.js
  src/Screens/Search/Search.js
  src/Screens/Settings/index.js
  src/Screens/index.js
  src/Utils/APIs.js
  yarn.lock
Labels: enhancement, Dependencies, Bug fix, Review effort [1-5]: 5

#10 Unable to launch the application
  android/app/src/main/java/com/inknest/MainActivity.kt
Labels: Bug fix, Review effort [1-5]: 2

#11 Bug fixed in video and added iPad support, fixed grid view
  ios/InkNest.xcodeproj/project.pbxproj
  ios/InkNest/Info.plist
  ios/Podfile.lock
  src/Components/UIComp/ComicBookFooter.js
  src/Components/UIComp/ComicBookHeader.js
  src/Components/UIComp/GridList.js
  src/Components/UIComp/HomeRenderItem.js
  src/Screens/Anime/Details/index.js
  src/Screens/Anime/Home/AnimeHome.js
  src/Screens/Anime/Home/ViewAll.js
  src/Screens/Anime/Video/index.js
  src/Screens/Comic/Book/ComicBook.js
  src/Screens/Comic/Details/ComicDetails.js
  src/Screens/Comic/Home/Home.js
Labels: enhancement, feature, Bug fix, Review effort [1-5]: 4

#12 chore: add cleanup for event listener to prevent memory leaks
  src/Components/UIComp/GridList.js
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#13 chore: refactor the conditional navigation logic to reduce redundancy and improve code readability
  ios/InkNest.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/Components/UIComp/HomeRenderItem.js
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#14 Code Cleanup and New State Management in AnimeHome Component
  src/Screens/Anime/Home/AnimeHome.js
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#15 New Features and Bug Fixes
  docs/src/pages/index.js
  ios/InkNest.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/Components/UIComp/HomeRenderItem.js
  src/Navigation/NavigationService.js
  src/Redux/Actions/GlobalActions.js
  src/Redux/Reducers/index.js
  src/Screens/AboutUs/index.js
  src/Screens/Anime/Details/index.js
  src/Screens/Anime/Home/AnimeHome.js
  src/Screens/Anime/Video/index.js
  src/Screens/Comic/Details/ComicDetails.js
  src/Screens/Settings/index.js
Labels: documentation, enhancement, Bug fix, Review effort [1-5]: 4

#16 chore: Replace with new bottom tabbar
  ios/InkNest.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/Navigation/AppNavigation.js
  src/Navigation/BottomNavigation.js
  src/Navigation/BottomNavigation/Components/AnimatedTabBarNavigator.tsx
  src/Navigation/BottomNavigation/Components/ResourceSavingScene.tsx
  src/Navigation/BottomNavigation/Components/TabBarElement.tsx
  src/Navigation/BottomNavigation/Components/UIComponents.ts
  src/Navigation/BottomNavigation/Components/index.ts
  src/Navigation/BottomNavigation/Components/types.tsx
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#17 CBZ and CBR file reader
  .gitignore
  ios/InkNest.xcodeproj/project.pbxproj
  ios/InkNest/PrivacyInfo.xcprivacy
  ios/Podfile.lock
  package.json
  src/Components/UIComp/GalleryPopup.js
  src/Constants/Navigation.js
  src/Navigation/BottomNavigation.js
  src/Screens/Comic/LocalComic/example.index.js
  src/Screens/Comic/index.js
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, Other
