Repository p2devs/InkNest, pull requests merged in 2024-11, with the labels that each got.

#23 chore: Enhance documentation, styling, and update dependencies
  README.md
  docs/README.md
  docs/docusaurus.config.js
  docs/package.json
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  package.json
  src/Screens/AboutUs/index.js
  yarn.lock
Labels: documentation, enhancement, style

#24 feat: add sorting functionality to comic listing
  src/Screens/Comic/Details/ComicDetails.js
Labels: Review effort [1-5]: 2

#25 Fix anime video streaming URL and update project settings
  ios/InkNest.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/Screens/Anime/Video/index.js
  yarn.lock
Labels: Bug
